const translations = {
  en: {
    "nav.framework": "Framework",
    "nav.tools": "Tools",
    "nav.intent": "Intent",
    "nav.sop": "30-Day SOP",
    "nav.validation": "Validation",
    "nav.contact": "Contact",
    "hero.eyebrow": "SEO & GEO Strategy Portfolio",
    "hero.title": "Making brands easier to find, understand, and trust.",
    "hero.lede": "I design content systems that help brands show up clearly across search engines and AI answer engines. My work connects search intent, content architecture, trust signals, and practical growth measurement.",
    "hero.primaryCta": "See the practical workflow",
    "hero.secondaryCta": "View the 30-day SOP",
    "hero.note": "This page uses public knowledge and fictional examples. No client names or private projects are shown.",
    "map.title": "Visibility System",
    "map.status": "Search + AI ready",
    "map.node1": "Product truth",
    "map.node2": "Search intent",
    "map.node3": "Topic structure",
    "map.node4": "Trust signals",
    "map.node5": "AI answer readiness",
    "map.metric1Label": "Pages",
    "map.metric1": "Use case, FAQ, compare",
    "map.metric2Label": "Signals",
    "map.metric2": "Clear claims, sources, schema",
    "map.metric3Label": "Review",
    "map.metric3": "Indexing, clicks, AI mentions",
    "intro.card1Title": "SEO Strategy",
    "intro.card1Body": "I turn vague topics into pages that match what people actually search for: questions, comparisons, use cases, and buying or decision moments.",
    "intro.card2Title": "GEO / AI Search",
    "intro.card2Body": "I structure content so AI tools can understand the brand, summarize it accurately, and find clear answers worth citing.",
    "intro.card3Title": "Content Architecture",
    "intro.card3Body": "I connect pillar pages, supporting articles, FAQs, comparison pages, and trust pages into one readable system.",
    "framework.kicker": "Framework",
    "framework.title": "SEO helps people find you. GEO helps AI understand and recommend you.",
    "framework.body": "I do not treat GEO as a magic trick. I treat it as clear information design: make the brand easier to crawl, easier to understand, easier to verify, and easier to quote.",
    "framework.item1Title": "Search intent before keywords",
    "framework.item1Body": "The first question is not “what keyword do we want?” It is “what problem is the user trying to solve, and what page would genuinely help?”",
    "framework.item2Title": "Content structure before content volume",
    "framework.item2Body": "More pages are not automatically better. A strong system has clear topic relationships, internal links, and pages with distinct jobs.",
    "framework.item3Title": "Trust signals before claims",
    "framework.item3Body": "AI search and human readers both need proof: definitions, examples, sources, author context, updated pages, and grounded comparisons.",
    "framework.item4Title": "Measurement before opinion",
    "framework.item4Body": "I would track indexing, impressions, click-through rate, ranking movement, branded queries, AI answer accuracy, and conversion quality.",
    "tools.kicker": "Tool Stack",
    "tools.title": "Tools are grouped by the question they answer.",
    "tools.body": "I do not start with tools. I start with the decision I need to make, then choose the tool that can verify it.",
    "tools.item1Title": "Find demand",
    "tools.item1Body": "Google Search Console, Google Trends, Google and Bing search results, Search Console query exports, and competitor SERP notes.",
    "tools.item1Use": "Use when deciding what users already search for and which topics deserve pages.",
    "tools.item2Title": "Audit pages",
    "tools.item2Body": "Screaming Frog or a similar crawler, PageSpeed Insights, browser inspection, sitemap checks, and Schema Markup Validator.",
    "tools.item2Use": "Use when checking whether pages can be crawled, understood, loaded quickly, and marked up clearly.",
    "tools.item3Title": "Test AI search",
    "tools.item3Body": "ChatGPT Search, Perplexity, Google AI Overviews, and manual prompt sets for brand, category, comparison, and use-case questions.",
    "tools.item3Use": "Use when checking whether AI systems explain the product correctly or miss important pages.",
    "tools.item4Title": "Measure outcomes",
    "tools.item4Body": "GA4, Looker Studio, Google Sheets, UTM tracking, CTA clicks, signups, demo requests, and saved workflow events.",
    "tools.item4Use": "Use when judging whether visibility brings useful users, not just more visitors.",
    "intent.kicker": "Search Intent",
    "intent.title": "I classify searches by the decision behind the words.",
    "intent.body": "A keyword is only useful after I understand what the user wants next: learn, compare, choose, trust, or take action.",
    "intent.item1Label": "Learn",
    "intent.item1Title": "What is GEO?",
    "intent.item1Body": "The page should define the concept, explain why it matters, and give beginner-friendly examples.",
    "intent.item2Label": "How to",
    "intent.item2Title": "How to optimize for AI search",
    "intent.item2Body": "The page should give steps, tools, before/after checks, and a clear workflow.",
    "intent.item3Label": "Compare",
    "intent.item3Title": "SEO vs GEO",
    "intent.item3Body": "The page should help users see differences, overlap, tradeoffs, and when each matters.",
    "intent.item4Label": "Decide",
    "intent.item4Title": "Best AI SEO tools",
    "intent.item4Body": "The page should compare options, use cases, pricing signals, and who each tool is best for.",
    "intent.item5Label": "Trust",
    "intent.item5Title": "Brand + pricing / reviews",
    "intent.item5Body": "The page should reduce doubt with proof, details, FAQs, security notes, and direct next steps.",
    "intent.item6Label": "Support",
    "intent.item6Title": "How do I connect X?",
    "intent.item6Body": "The page should solve a specific problem quickly and link back to the main product journey.",
    "workflow.kicker": "Audit Workflow",
    "workflow.title": "A practical process from diagnosis to roadmap.",
    "workflow.body": "This is the kind of workflow I would use before recommending content, page changes, or GEO experiments.",
    "workflow.step1Title": "Clarify the goal",
    "workflow.step1Body": "Traffic, signups, demo requests, trust, brand discovery, or a specific product category.",
    "workflow.step2Title": "Map search intent",
    "workflow.step2Body": "Group queries into learning, comparison, decision, brand, and support needs.",
    "workflow.step3Title": "Review content coverage",
    "workflow.step3Body": "Find missing use cases, thin pages, unclear answers, and content that competes with itself.",
    "workflow.step4Title": "Check entity clarity",
    "workflow.step4Body": "Make sure the brand, product, audience, category, and use cases are described consistently.",
    "workflow.step5Title": "Inspect technical basics",
    "workflow.step5Body": "Indexability, metadata, page speed, mobile layout, internal links, canonicals, and schema.",
    "workflow.step6Title": "Test AI answer readiness",
    "workflow.step6Body": "Check whether AI search tools can explain the product accurately and find useful sources.",
    "workflow.step7Title": "Prioritize the roadmap",
    "workflow.step7Body": "Rank fixes by impact, effort, confidence, and how close they are to business outcomes.",
    "table.col1": "Area",
    "table.col2": "What I check",
    "table.col3": "Why it matters",
    "table.r1c1": "Search intent",
    "table.r1c2": "Does each page answer a real question or decision?",
    "table.r1c3": "Keeps content useful instead of broad and vague.",
    "table.r2c1": "Entity signals",
    "table.r2c2": "Is the product category, audience, and value clearly named?",
    "table.r2c3": "Helps search engines and AI systems understand what the brand is.",
    "table.r3c1": "Answer format",
    "table.r3c2": "Are definitions, steps, examples, and FAQs easy to quote?",
    "table.r3c3": "Improves snippet quality and AI-answer readability.",
    "table.r4c1": "Internal links",
    "table.r4c2": "Do related pages point to each other in a logical path?",
    "table.r4c3": "Builds topic authority and helps users keep moving.",
    "sop.kicker": "30-Day SOP",
    "sop.title": "AI product SEO + GEO launch plan.",
    "sop.body": "A practical first-month operating plan for turning an AI product from “hard to explain” into searchable, understandable, and measurable content.",
    "sop.week1Label": "Week 1",
    "sop.week1Title": "Diagnose demand and positioning",
    "sop.week1Body": "Clarify the product, target users, use cases, search demand, competitor SERPs, and AI-search baseline.",
    "sop.week1Deliverable": "Deliverables: audit sheet, intent map, priority page list.",
    "sop.week2Label": "Week 2",
    "sop.week2Title": "Design page and content structure",
    "sop.week2Body": "Plan product pages, use-case pages, comparison pages, FAQ/glossary pages, CTA logic, and internal links.",
    "sop.week2Deliverable": "Deliverables: content map, page briefs, FAQ bank.",
    "sop.week3Label": "Week 3",
    "sop.week3Title": "Build and optimize pages",
    "sop.week3Body": "Write clear pages, add examples, optimize titles and headings, check mobile UX, indexability, schema, and speed.",
    "sop.week3Deliverable": "Deliverables: optimized pages, metadata, technical notes.",
    "sop.week4Label": "Week 4",
    "sop.week4Title": "Launch, measure, and iterate",
    "sop.week4Body": "Submit pages, track indexing and clicks, test AI answers, review conversions, and plan next-month priorities.",
    "sop.week4Deliverable": "Deliverables: performance review, AI visibility notes, roadmap.",
    "signals.kicker": "Measurement",
    "signals.title": "The goal is not just traffic. It is useful visibility.",
    "signals.body": "I would review both search performance and whether AI tools describe the product correctly. More traffic is only valuable when it brings better understanding, better users, or better conversion.",
    "signals.item1Title": "Search performance",
    "signals.item1Body": "Indexing, impressions, ranking movement, CTR, query mix, and landing page engagement.",
    "signals.item2Title": "AI answer quality",
    "signals.item2Body": "Can ChatGPT Search, Perplexity, or AI Overviews explain the product accurately and cite useful pages?",
    "signals.item3Title": "Conversion quality",
    "signals.item3Body": "Which pages lead to signups, demos, saved templates, contact actions, or deeper product exploration?",
    "signals.item4Title": "Iteration rhythm",
    "signals.item4Body": "Use the data to update page structure, examples, FAQs, internal links, and topic priorities.",
    "contact.kicker": "About",
    "contact.title": "A bilingual growth operator focused on AI-era visibility.",
    "contact.body": "I bring together bilingual content strategy, AI product understanding, creator/community growth, and practical SEO/GEO workflows. My focus is helping complex products become easier for people and AI systems to understand.",
    "contact.cardTitle": "Contact",
    "contact.note": "Available for growth, content strategy, SEO/GEO, creator/community, and AI product-facing roles."
  },
  zh: {
    "nav.framework": "方法论",
    "nav.tools": "工具",
    "nav.intent": "搜索意图",
    "nav.sop": "30 天 SOP",
    "nav.validation": "验证方法",
    "nav.contact": "联系",
    "hero.eyebrow": "SEO / GEO 能力展示站",
    "hero.title": "让别人更容易搜到你、看懂你、信任你。",
    "hero.lede": "我关注的是：一个品牌、产品或个人，怎样通过更清楚的内容结构，在 Google、百度、必应以及 AI 搜索里被正确理解。我的方法会从用户到底在搜什么、页面应该怎么写、证据怎么呈现、效果怎么判断这几步来拆。",
    "hero.primaryCta": "查看实操流程",
    "hero.secondaryCta": "查看 30 天 SOP",
    "hero.note": "本页只使用公开知识和虚构示例，不展示客户名称或私人项目。",
    "map.title": "让内容被看见的路径",
    "map.status": "适合搜索和 AI 阅读",
    "map.node1": "先讲清楚产品",
    "map.node2": "理解用户在搜什么",
    "map.node3": "安排页面结构",
    "map.node4": "补足信任证据",
    "map.node5": "让 AI 更容易读懂",
    "map.metric1Label": "页面",
    "map.metric1": "场景页、问答页、对比页",
    "map.metric2Label": "证据",
    "map.metric2": "清楚表达、来源、页面标记",
    "map.metric3Label": "效果",
    "map.metric3": "是否收录、有人点击、AI 是否提到",
    "intro.card1Title": "SEO 策略",
    "intro.card1Body": "我会先看用户会搜什么，再规划对应页面。",
    "intro.card2Title": "GEO / AI 搜索",
    "intro.card2Body": "GEO 可以理解为：让 AI 搜索工具更容易读懂你，并在回答相关问题时正确提到你。",
    "intro.card3Title": "内容怎么组织",
    "intro.card3Body": "我会把首页、介绍页、问答页、对比页和信任信息串起来，让用户和搜索系统都能看明白。",
    "framework.kicker": "方法论",
    "framework.title": "SEO 是让人搜得到你，GEO 是让 AI 也能正确理解你。",
    "framework.body": "我不会把 GEO 说得很玄。简单讲，它就是把内容整理得更清楚：搜索引擎能抓到，用户能看懂，AI 能总结，别人也能判断你说的是否可信。",
    "framework.item1Title": "先看用户想解决什么，再看关键词",
    "framework.item1Body": "真正重要的不是“我要抢哪个词”，而是“用户输入这句话时，他到底想知道什么、比较什么、决定什么”。",
    "framework.item2Title": "先把内容关系理顺，再去写很多文章",
    "framework.item2Body": "页面越多不一定越好。一个好网站应该让人知道：先看哪一页，再看哪一页，每一页分别解决什么问题。",
    "framework.item3Title": "先给证据，再写宣传语",
    "framework.item3Body": "不管是人还是 AI，都不能只看口号。定义、例子、来源、作者介绍、更新时间、真实对比，都是让内容更可信的东西。",
    "framework.item4Title": "先想清楚怎么判断效果",
    "framework.item4Body": "我会看页面有没有被收录、有没有曝光和点击、排名有没有变化、AI 回答是否准确，以及这些访问有没有带来有效用户。",
    "tools.kicker": "工具怎么用",
    "tools.title": "我不会为了用工具而用工具，而是先看要回答什么问题。",
    "tools.body": "每个工具都有明确用途：有的帮我发现用户在搜什么，有的帮我检查页面问题，有的帮我测试 AI 是否读懂，有的帮我判断结果有没有价值。",
    "tools.item1Title": "发现用户需求",
    "tools.item1Body": "Google Search Console、Google Trends、Google / Bing 搜索结果、搜索词导出表、竞品搜索结果记录。",
    "tools.item1Use": "用来判断：用户已经在搜什么，哪些问题值得单独做页面。",
    "tools.item2Title": "检查页面基础",
    "tools.item2Body": "Screaming Frog 或类似爬虫工具、PageSpeed Insights、浏览器检查、sitemap 检查、Schema Markup Validator。",
    "tools.item2Use": "用来判断：页面能不能被抓取，标题是否清楚，速度和手机端体验是否正常，结构化标记是否有效。",
    "tools.item3Title": "测试 AI 搜索",
    "tools.item3Body": "ChatGPT Search、Perplexity、Google AI Overviews，以及一组固定测试问题：品牌、品类、对比、使用场景。",
    "tools.item3Use": "用来判断：AI 有没有讲对这个产品，有没有漏掉重要页面，是否把竞品讲得更清楚。",
    "tools.item4Title": "衡量实际结果",
    "tools.item4Body": "GA4、Looker Studio、Google Sheets、UTM、按钮点击、注册、预约演示、咨询和模板保存数据。",
    "tools.item4Use": "用来判断：搜索曝光有没有带来真正有价值的用户，而不只是访问量变多。",
    "intent.kicker": "搜索意图",
    "intent.title": "我会判断用户搜这句话时，心里真正想做什么。",
    "intent.body": "一个关键词本身不够重要，重要的是它背后的需求：用户是想了解、想学习步骤、想比较、想做决定，还是已经准备行动。",
    "intent.item1Label": "想了解",
    "intent.item1Title": "什么是 GEO？",
    "intent.item1Body": "页面应该先讲清楚概念，再解释为什么重要，并给新手也能看懂的例子。",
    "intent.item2Label": "想操作",
    "intent.item2Title": "怎么优化 AI 搜索？",
    "intent.item2Body": "页面应该给步骤、工具、检查方法和一个能照着做的流程。",
    "intent.item3Label": "想比较",
    "intent.item3Title": "SEO 和 GEO 有什么区别？",
    "intent.item3Body": "页面应该讲清楚两者差别、重叠部分、适合场景，以及什么时候该优先做哪一个。",
    "intent.item4Label": "想选择",
    "intent.item4Title": "有哪些 AI SEO 工具？",
    "intent.item4Body": "页面应该比较不同工具适合谁、解决什么问题、价格和使用场景。",
    "intent.item5Label": "想确认",
    "intent.item5Title": "品牌名 + 价格 / 评价",
    "intent.item5Body": "页面应该减少疑虑：提供证明、细节、常见问题、安全说明和下一步行动。",
    "intent.item6Label": "想解决问题",
    "intent.item6Title": "怎么连接某个工具？",
    "intent.item6Body": "页面应该快速解决一个具体问题，同时把用户带回主产品路径。",
    "workflow.kicker": "检查流程",
    "workflow.title": "我会这样一步步检查一个网站。",
    "workflow.body": "在建议改标题、改页面、写文章或做 GEO 实验之前，我会先用这个流程判断：问题到底出在哪里，哪一步最值得先做。",
    "workflow.step1Title": "明确业务目标",
    "workflow.step1Body": "先分清楚目标是要流量、注册、咨询、预约演示、建立信任，还是让更多人知道这个品牌。",
    "workflow.step2Title": "看用户会怎么搜",
    "workflow.step2Body": "把搜索需求分成几类：想了解、想比较、准备下单、搜索品牌名、遇到问题要解决。",
    "workflow.step3Title": "检查内容覆盖",
    "workflow.step3Body": "看有没有漏掉重要问题，哪些页面内容太薄，哪些回答不够清楚，哪些页面在重复讲同一件事。",
    "workflow.step4Title": "检查品牌信息是否说清楚",
    "workflow.step4Body": "确认别人一眼能不能看懂：你是谁，做什么，适合谁，解决什么问题，和别人有什么不同。",
    "workflow.step5Title": "检查技术基础",
    "workflow.step5Body": "看页面能不能被搜索引擎收录，标题描述是否清楚，手机端是否好看，速度、链接和结构化标记是否正常。",
    "workflow.step6Title": "测试 AI 能不能读懂",
    "workflow.step6Body": "用 AI 搜索工具测试：它能不能准确解释这个产品？会不会说错？能不能找到合适的来源页面？",
    "workflow.step7Title": "排列优先级",
    "workflow.step7Body": "最后不是什么都改，而是按影响大小、执行成本、确定性和业务价值来排先后顺序。",
    "table.col1": "维度",
    "table.col2": "我会检查什么",
    "table.col3": "为什么重要",
    "table.r1c1": "用户需求",
    "table.r1c2": "这个页面是否真的回答了用户关心的问题？",
    "table.r1c3": "避免页面看起来很完整，但其实没有解决任何具体问题。",
    "table.r2c1": "品牌信息",
    "table.r2c2": "产品是什么、给谁用、价值是什么，是否说得清楚？",
    "table.r2c3": "帮助搜索引擎和 AI 判断这个品牌到底属于什么领域。",
    "table.r3c1": "回答方式",
    "table.r3c2": "定义、步骤、例子和常见问题是否清楚？",
    "table.r3c3": "让用户更容易读懂，也让 AI 更容易引用正确内容。",
    "table.r4c1": "内部链接",
    "table.r4c2": "相关页面之间有没有自然的跳转路径？",
    "table.r4c3": "帮助用户继续看，也让搜索系统理解这些内容之间的关系。",
    "sop.kicker": "30 天 SOP",
    "sop.title": "AI 产品 SEO + GEO 30 天落地流程。",
    "sop.body": "这个流程适合一个还没把搜索内容做起来的 AI 产品：先弄清楚用户怎么搜，再设计页面，接着上线内容，最后用搜索数据和 AI 回答来验证。",
    "sop.week1Label": "第 1 周",
    "sop.week1Title": "诊断需求和产品定位",
    "sop.week1Body": "讲清楚产品是什么、给谁用、解决什么问题；整理核心使用场景、搜索需求、竞品搜索结果和 AI 搜索当前怎么回答。",
    "sop.week1Deliverable": "交付物：检查表、搜索意图地图、优先页面清单。",
    "sop.week2Label": "第 2 周",
    "sop.week2Title": "设计页面和内容结构",
    "sop.week2Body": "规划产品页、使用场景页、对比页、常见问题页、术语解释页、CTA 和内部链接，让用户和搜索系统都能顺着看明白。",
    "sop.week2Deliverable": "交付物：内容地图、页面 brief、FAQ 题库。",
    "sop.week3Label": "第 3 周",
    "sop.week3Title": "制作内容并优化页面",
    "sop.week3Body": "写清楚页面文案，补充定义、步骤和例子，优化标题和小标题，检查手机端、可收录性、结构化标记和速度。",
    "sop.week3Deliverable": "交付物：优化后的页面、SEO 标题描述、技术检查记录。",
    "sop.week4Label": "第 4 周",
    "sop.week4Title": "上线、验证、安排下一轮",
    "sop.week4Body": "提交页面，追踪收录、曝光和点击；测试 AI 回答是否准确；看注册、咨询等有效动作，再排下个月优化优先级。",
    "sop.week4Deliverable": "交付物：30 天复盘、AI 搜索表现记录、下月路线图。",
    "signals.kicker": "怎么判断效果",
    "signals.title": "目标不只是有流量，而是让对的人看懂你。",
    "signals.body": "我会同时看搜索数据和 AI 回答质量。访问量当然重要，但更重要的是：来的人是不是对，AI 有没有讲对，页面有没有帮用户做决定。",
    "signals.item1Title": "搜索表现",
    "signals.item1Body": "看页面有没有被收录，有多少曝光和点击，排名有没有变化，用户点进来后有没有继续看。",
    "signals.item2Title": "AI 有没有讲对",
    "signals.item2Body": "看 ChatGPT Search、Perplexity 或 Google AI 回答能不能准确解释产品，有没有引用到合适页面。",
    "signals.item3Title": "有没有带来有效动作",
    "signals.item3Body": "看哪些页面带来注册、咨询、预约、保存模板、点击联系或更深入的浏览。",
    "signals.item4Title": "持续调整",
    "signals.item4Body": "根据数据更新页面结构、例子、常见问题、内部链接和下一批内容重点。",
    "contact.kicker": "关于我",
    "contact.title": "我关注的是：复杂产品怎样被更多人看懂。",
    "contact.body": "我把中英文内容表达、AI 产品理解、创作者/社区增长和 SEO/GEO 实操方法结合起来。我的重点是帮助复杂产品讲清楚自己，让普通用户、搜索引擎和 AI 工具都更容易理解。",
    "contact.cardTitle": "联系",
    "contact.note": "适合增长、内容策略、SEO/GEO、创作者/社区运营，以及 AI 产品相关的非技术岗位。"
  }
};

const languageButtons = document.querySelectorAll("[data-lang-option]");
const translatableNodes = document.querySelectorAll("[data-i18n]");

function setLanguage(lang, persist = true) {
  const dictionary = translations[lang] || translations.en;
  document.documentElement.lang = lang === "zh" ? "zh-CN" : "en";
  document.body.dataset.lang = lang;
  translatableNodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });
  languageButtons.forEach((button) => {
    button.setAttribute("aria-pressed", String(button.dataset.langOption === lang));
  });
  if (persist) {
    localStorage.setItem("seoGeoPortfolioLanguage", lang);
  }
}

languageButtons.forEach((button) => {
  button.addEventListener("click", () => setLanguage(button.dataset.langOption));
});

const requestedLanguage = new URLSearchParams(window.location.search).get("lang");
const savedLanguage = localStorage.getItem("seoGeoPortfolioLanguage");
if (requestedLanguage === "zh" || requestedLanguage === "en") {
  setLanguage(requestedLanguage, false);
} else {
  setLanguage(savedLanguage === "zh" ? "zh" : "en");
}

if (window.lucide) {
  window.lucide.createIcons();
}
